### ISSUE TITLE
The application crashes after 20 minutes of operation.

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForAndroid#492]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.10

### Operating mode

Integration with AdGuard

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Environment

```markdown
- OS: Android 8.1.0 MIUI MiRoom 10.3.2
- Device: MiPad 4 Plus
```

### Root access

- [X] yes, I have it

### Issue Details

After 20 minutes work for youtube, the VPN connection is loss. The tray shows that the connection is stable. You open the AdguardVPN application and the application crashes.

### Expected Behavior

The application is expected to operate stably.

### Actual Behavior

The application crashes.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Logs have been sent to qa@adguard.com

**Comment by Eksol** [comment]
error log

java.lang.RuntimeException: Adding window failed
at android.view.ViewRootImpl.setView([ViewRootImpl.java:764](https://vk.com/away.php?to=http%3A%2F%2FViewRootImpl.java%3A764&cc_key=))
at android.view.WindowManagerGlobal.addView([WindowManagerGlobal.java:356](https://vk.com/away.php?to=http%3A%2F%2FWindowManagerGlobal.java%3A356&cc_key=))
at android.view.WindowManagerImpl.addView([WindowManagerImpl.java:94](https://vk.com/away.php?to=http%3A%2F%2FWindowManagerImpl.java%3A94&cc_key=))
at android.app.ActivityThread.handleResumeActivity([ActivityThread.java:3716](https://vk.com/away.php?to=http%3A%2F%2FActivityThread.java%3A3716&cc_key=))
at android.app.ActivityThread.handleLaunchActivity([ActivityThread.java:2901](https://vk.com/away.php?to=http%3A%2F%2FActivityThread.java%3A2901&cc_key=))
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage([ActivityThread.java:1616](https://vk.com/away.php?to=http%3A%2F%2FActivityThread.java%3A1616&cc_key=))
at android.os.Handler.dispatchMessage([Handler.java:106](https://vk.com/away.php?to=http%3A%2F%2FHandler.java%3A106&cc_key=))
at android.os.Looper.loop([Looper.java:173](https://vk.com/away.php?to=http%3A%2F%2FLooper.java%3A173&cc_key=))
at android.app.ActivityThread.main([ActivityThread.java:6651](https://vk.com/away.php?to=http%3A%2F%2FActivityThread.java%3A6651&cc_key=))
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:547](https://vk.com/away.php?to=http%3A%2F%2FRuntimeInit.java%3A547&cc_key=))
at com.android.internal.os.ZygoteInit.main([ZygoteInit.java:822](https://vk.com/away.php?to=http%3A%2F%2FZygoteInit.java%3A822&cc_key=))
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact([Binder.java:774](https://vk.com/away.php?to=http%3A%2F%2FBinder.java%3A774&cc_key=))
at android.view.IWindowSession$Stub$Proxy.addToDisplay([IWindowSession.java:791](https://vk.com/away.php?to=http%3A%2F%2FIWindowSession.java%3A791&cc_key=))
at android.view.ViewRootImpl.setView([ViewRootImpl.java:752](https://vk.com/away.php?to=http%3A%2F%2FViewRootImpl.java%3A752&cc_key=))
... 12 more

**Comment by Versty** [comment]
@Eksol Thank you for reporting! 

In order to investigate this problem, we would like to take a look at the logs and system bug report from your device. 
Please follow the steps below: 

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Extended*.

2. Wait for the crash to be reproduced, then remember the exact time it happened.

3. Collect application logs:
*Settings -> General -> Advanced -> Export logs and system info*.

4. Collect system logs according to [this guide](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/).

4. Send both files to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `492` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@Eksol Have you sent logs?

**Comment by Eksol** [comment]
> @Eksol Have you sent logs?

send

**Comment by Versty** [comment]
@Eksol Unfortunately, the default level of logging is not enough to figure out the cause of the crash. 
Please follow the steps from the [comment](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/492#issuecomment-2407373998) above.

**Comment by Versty** [comment]
@Eksol any updates?

**Comment by Eksol** [comment]
> any updates?

I reinstalled the firmware on my tablet. The problem went away. I don't know why this happened. Last time, vpn adguard crashed and the network stopped working. 
There are other problems now.
Low speed.

**Comment by Versty** [comment]
@Eksol

 > I reinstalled the firmware on my tablet. The problem went away.
 
 Glad to hear that the problem is resolved.

Please keep the `Send anonymous crash reports` option enabled, so we could have a crash log in case the crash happens again. 

Let's discuss problems with low speed in separate issue https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/498
